-- F1 Paddock SL — comments table
--
-- Run this in the Supabase dashboard → SQL Editor. Safe to re-run: every
-- statement converges on the intended state (if not exists / drop if exists /
-- conditional DO blocks), so you can paste it again whenever.
--
-- It upgrades a pre-existing plain `comments` table in place rather than
-- dropping it, so nothing is lost if rows already exist.
--
-- SECURITY NOTE: the anon key is exposed in the browser bundle
-- (NEXT_PUBLIC_SUPABASE_ANON_KEY), so anyone can talk to this table directly
-- with it. Row Level Security is the ONLY thing stopping them. Never grant
-- `update` or `delete` to `anon` — moderation has to go through the service
-- role / SQL editor, otherwise anyone could delete every comment on the site.
-- Never put the service_role key in a NEXT_PUBLIC_ variable.

-- ---------------------------------------------------------------------------
-- 1. Table + columns
-- ---------------------------------------------------------------------------

create table if not exists public.comments (
  id          bigint      generated by default as identity primary key,
  post_id     text        not null,
  author      text        not null,
  body        text        not null,
  target_type text        not null,
  target_id   text        not null,
  created_at  timestamptz not null default now()
);

-- No-ops when the table was just created above. These are what repair a table
-- that already existed without them — defaults are required so this doesn't
-- fail if the table already holds rows.
alter table public.comments add column if not exists post_id    text        not null default '';
alter table public.comments add column if not exists author     text        not null default '';
alter table public.comments add column if not exists body       text        not null default '';
alter table public.comments add column if not exists created_at timestamptz not null default now();

-- target_type/target_id are a polymorphic reference pair that already existed
-- on this table (they look built for Facebook comments) and are NOT NULL. The
-- app fills them in rather than us relaxing the constraint. Defaults let this
-- statement succeed if the table already holds rows.
alter table public.comments add column if not exists target_type text not null default 'post';
alter table public.comments add column if not exists target_id   text not null default '';

-- The text columns must always be supplied explicitly. (Dropped again right
-- after being added above, so the API can't silently insert empty rows.)
alter table public.comments alter column post_id     drop default;
alter table public.comments alter column author      drop default;
alter table public.comments alter column body        drop default;
alter table public.comments alter column target_type drop default;
alter table public.comments alter column created_at  set default now();

-- A table that predates this script may have a plain `bigint` id with no
-- sequence, which makes every INSERT fail. Only wire one up when the column
-- has neither a default nor an identity.
--
-- Note: identity columns report column_default = NULL in information_schema
-- (the sequence lives in pg_attribute.attidentity, not in a default), so that
-- view cannot be used to detect them — ask pg_attribute directly.
do $$
declare has_default boolean;
begin
  select count(*) > 0 into has_default
  from pg_attribute
  where attrelid = 'public.comments'::regclass
    and attname   = 'id'
    and attnum > 0
    and not attisdropped
    and (atthasdef or attidentity <> '');

  if not has_default then
    create sequence if not exists public.comments_id_seq;
    alter table public.comments alter column id set default nextval('public.comments_id_seq');
    -- Start past any rows inserted by hand while the sequence was missing.
    perform setval(
      'public.comments_id_seq',
      coalesce((select max(id) from public.comments), 0) + 1,
      false
    );
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- 2. Index — comments are always fetched per-post, newest first
-- ---------------------------------------------------------------------------

create index if not exists comments_post_id_created_at_idx
  on public.comments (post_id, created_at desc);

-- ---------------------------------------------------------------------------
-- 3. Constraints — same bounds the API route enforces, so a hand-crafted
--    request made with the anon key can't bypass them either
-- ---------------------------------------------------------------------------

alter table public.comments drop constraint if exists comments_author_length;
alter table public.comments add constraint comments_author_length
  check (char_length(author) between 1 and 40);

alter table public.comments drop constraint if exists comments_body_length;
alter table public.comments add constraint comments_body_length
  check (char_length(body) between 1 and 1000);

alter table public.comments drop constraint if exists comments_post_id_length;
alter table public.comments add constraint comments_post_id_length
  check (char_length(post_id) between 1 and 200);

-- ---------------------------------------------------------------------------
-- 4. Row Level Security
-- ---------------------------------------------------------------------------

alter table public.comments enable row level security;

-- Reads: comments are public content, so anon may select them.
drop policy if exists "comments are publicly readable" on public.comments;
create policy "comments are publicly readable"
  on public.comments for select
  to anon, authenticated
  using (true);

-- Writes: anonymous visitors may post. Length limits are duplicated here on
-- purpose — RLS is evaluated against the raw row, before the route trims input.
drop policy if exists "anonymous visitors may comment" on public.comments;
create policy "anonymous visitors may comment"
  on public.comments for insert
  to anon, authenticated
  with check (
    char_length(author) between 1 and 40
    and char_length(body) between 1 and 1000
    and char_length(post_id) between 1 and 200
  );

-- No update/delete policy for anon on purpose. See the security note above.

grant usage on schema public to anon, authenticated;
grant select, insert on table public.comments to anon, authenticated;
revoke update, delete on table public.comments from anon, authenticated;

-- ---------------------------------------------------------------------------
-- 5. Verify — relrowsecurity must be true
-- ---------------------------------------------------------------------------
-- select column_name, data_type, is_nullable, column_default
--   from information_schema.columns
--   where table_schema = 'public' and table_name = 'comments' order by ordinal_position;
--
-- select relname, relrowsecurity from pg_tables where tablename = 'comments';